{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
type: {{ .Values.secret.type | default "Opaque" }}
{{- if or .Values.secret.stringData .Values.secret.files .Values.secret.filesGlob }}
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range .Values.secret.files }}
  {{ .key }}: |
{{ .content | indent 4 }}
  {{- end }}
  {{- if .Values.secret.filesGlob }}
  {{- $files := .Files.Glob .Values.secret.filesGlob }}
  {{- if $files }}
  {{- range $path, $content := $files }}
  {{ base $path }}: |
{{ $content | toString | indent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.secret.data }}
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
